name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/config-tester.yml@main
